# Generated by Django 2.1.4 on 2020-06-10 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_status', models.CharField(choices=[(1, 'ثبت شده'), (2, 'در حال بارگیری'), (3, 'فرستاده شده'), (4, 'تحویل داده شده')], default=1, max_length=1, verbose_name='order status')),
                ('order_info', models.TextField(verbose_name='order info')),
                ('transportation_cost', models.FloatField(default=0, verbose_name='transportation cost')),
                ('delivery_status', models.BooleanField(default=False, verbose_name='delivery status')),
                ('source_address', models.TextField(verbose_name='source address')),
                ('destination_address', models.TextField(verbose_name='destination address')),
                ('weight', models.FloatField(default=0, verbose_name='order weight')),
            ],
        ),
    ]
