# Generated by Django 3.0.8 on 2020-08-20 19:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vehicles', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_code', models.CharField(blank=True, max_length=32, null=True, unique=True)),
                ('is_load', models.BooleanField(default=False, verbose_name='Is Load')),
                ('order_status', models.CharField(choices=[('1', 'submited'), ('2', 'loading'), ('3', 'sending'), ('4', 'delivered')], default='1', max_length=1, verbose_name='Order Status')),
                ('destination_address', models.TextField(null=True, verbose_name='Destination Address')),
                ('transportation_cost', models.FloatField(default=0, null=True, verbose_name='Transportation Cost')),
                ('latitude', models.FloatField(default=-1)),
                ('longitude', models.FloatField(default=-1)),
                ('rating', models.IntegerField(blank=True, null=True)),
                ('driver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='users.Driver', verbose_name='Driver')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='users.Customer', verbose_name='Owner')),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='vehicles.Vehicle', verbose_name='Vehicle')),
            ],
        ),
    ]
