# Generated by Django 3.0.8 on 2020-08-06 13:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0002_auto_20200806_1320'),
        ('orders', '0002_auto_20200806_1130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='vehicles.Vehicle', verbose_name='Vehicle'),
        ),
    ]
