# Generated by Django 3.0.8 on 2020-08-17 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20200815_1614'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_code',
            field=models.CharField(blank=True, max_length=32, null=True, unique=True),
        ),
    ]
