# Generated by Django 3.0.8 on 2020-08-18 11:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20200816_1848'),
        ('orders', '0004_order_order_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(default=3)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rate', to='orders.Order')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rate', to='users.Customer')),
            ],
        ),
    ]
