# Generated by Django 3.0.8 on 2020-08-18 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_auto_20200818_1622'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='rating',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Rate',
        ),
    ]
