# Generated by Django 3.0.8 on 2020-08-21 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Crash',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('crash_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'crash',
                'verbose_name_plural': 'crashes',
            },
        ),
    ]
