# Generated by Django 3.0.8 on 2020-08-21 16:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('vehicles', '0001_initial'),
        ('crashes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='crash',
            name='driver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crash', to='users.Driver'),
        ),
        migrations.AddField(
            model_name='crash',
            name='vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='crash', to='vehicles.Vehicle'),
        ),
    ]
