# Generated by Django 3.0.8 on 2020-08-15 03:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crashes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='crash',
            old_name='date',
            new_name='crash_date',
        ),
    ]
