# Generated by Django 3.0.8 on 2020-08-18 10:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20200816_1848'),
        ('vehicles', '0003_auto_20200818_1512'),
        ('crashes', '0002_auto_20200815_0319'),
    ]

    operations = [
        migrations.AddField(
            model_name='crash',
            name='vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='crash', to='vehicles.Vehicle'),
        ),
        migrations.AlterField(
            model_name='crash',
            name='driver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crash', to='users.Driver'),
        ),
    ]
