# Generated by Django 3.0.8 on 2020-08-15 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='vehicle_status',
            field=models.CharField(choices=[('1', 'Free'), ('2', 'Busy')], default='1', max_length=1, verbose_name='Vehicle Status'),
        ),
    ]
