# Generated by Django 3.0.8 on 2020-08-06 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='duty_no',
            field=models.IntegerField(default=0, verbose_name='Number of Duty'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='max_capacity',
            field=models.FloatField(default=0, verbose_name='Maximum Capacity'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='max_tolerable_weight',
            field=models.FloatField(default=0, verbose_name='Max Tolerable Weight'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='plate_no',
            field=models.CharField(blank=True, max_length=8, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='vehicle_status',
            field=models.CharField(default='1', max_length=1, verbose_name='Vehicle Status'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='vehicle_type',
            field=models.CharField(choices=[('1', 'heavy car'), ('2', 'automobile')], default='1', max_length=1, verbose_name='Vehicle Type'),
        ),
    ]
