# Generated by Django 3.0.8 on 2020-08-18 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0002_auto_20200815_0520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='vehicle_status',
            field=models.CharField(choices=[('1', 'Free'), ('2', 'Busy'), ('3', 'Crashed')], default='1', max_length=1, verbose_name='Vehicle Status'),
        ),
    ]
