# Generated by Django 3.0.8 on 2020-08-06 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0002_auto_20200806_1320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='plate_no',
            field=models.CharField(max_length=8, null=True, unique=True),
        ),
    ]
