# Generated by Django 3.0.8 on 2020-08-07 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='is_authorizer',
            field=models.BooleanField(default=False, verbose_name='Is Authorizer'),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='is_customer',
            field=models.BooleanField(default=False, verbose_name='Is Customer'),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='is_driver',
            field=models.BooleanField(default=False, verbose_name='Is Driver'),
        ),
    ]
