# Generated by Django 3.0.5 on 2020-08-01 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='driver',
            old_name='status',
            new_name='driver_status',
        ),
    ]
