# Generated by Django 3.0.8 on 2020-08-05 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='is_verified',
            field=models.BooleanField(default=False, verbose_name='Is Verified'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='driver_status',
            field=models.CharField(choices=[('1', 'Free'), ('2', 'Busy')], max_length=1, verbose_name='Driver Status'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Profile Picture'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='ranking',
            field=models.IntegerField(default=-1, verbose_name='Ranking'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='rating',
            field=models.FloatField(default=-1, verbose_name='Rating'),
        ),
    ]
