# Generated by Django 3.0.8 on 2020-08-06 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='national_id',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='National ID'),
        ),
    ]
