# Generated by Django 3.0.5 on 2020-07-31 01:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driver',
            name='ranking',
        ),
    ]
