# Generated by Django 3.0.8 on 2020-08-07 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200806_1556'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='birthday',
            field=models.DateField(null=True, verbose_name='Birthday'),
        ),
    ]
