# Generated by Django 3.0.5 on 2020-07-29 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_driver'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='status',
            field=models.CharField(choices=[('1', 'Free'), ('2', 'Busy')], max_length=1),
        ),
    ]
