# Generated by Django 2.1.4 on 2020-06-09 22:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0002_auto_20200609_2158'),
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('father_name', models.CharField(blank=True, max_length=20, verbose_name="Father's Name")),
                ('national_id', models.CharField(blank=True, max_length=10, verbose_name='National ID')),
                ('phone_no', models.CharField(blank=True, max_length=11, verbose_name='Phone Number')),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='drivermodel',
            name='user',
        ),
        migrations.DeleteModel(
            name='DriverModel',
        ),
    ]
