# Generated by Django 3.0.5 on 2020-07-31 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_driver_ranking'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='ranking',
            field=models.IntegerField(default=-1),
        ),
    ]
