# Generated by Django 2.1.4 on 2020-06-09 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200609_2205'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='salary',
            field=models.FloatField(default=0),
        ),
    ]
