# Generated by Django 3.0.8 on 2020-08-07 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_driver_birthday'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='birthday',
            field=models.DateField(null=True, verbose_name='Birthday'),
        ),
    ]
