# Generated by Django 3.0.8 on 2020-08-07 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_driver_is_driver'),
    ]

    operations = [
        migrations.AddField(
            model_name='authorizer',
            name='is_authorizer',
            field=models.BooleanField(default=True, verbose_name='Is Authorizer'),
        ),
        migrations.AddField(
            model_name='customer',
            name='is_customer',
            field=models.BooleanField(default=True, verbose_name='Is Customer'),
        ),
    ]
