# Generated by Django 3.0.5 on 2020-07-29 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('users', '0003_auto_20200729_1741'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermodel',
            name='user_ptr',
        ),
        migrations.DeleteModel(
            name='Driver',
        ),
        migrations.DeleteModel(
            name='Usermodel',
        ),
    ]
