# Generated by Django 3.0.8 on 2020-08-05 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200805_1504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='./static/profile_pictures', verbose_name='Profile Picture'),
        ),
    ]
