# Generated by Django 2.1.4 on 2020-06-09 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_driver_salary'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
