# Generated by Django 3.0.8 on 2020-08-05 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20200805_1505'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='latitude',
            field=models.FloatField(default=-1, verbose_name='Latitude'),
        ),
        migrations.AddField(
            model_name='driver',
            name='longitude',
            field=models.FloatField(default=-1, verbose_name='Longitude'),
        ),
    ]
