# Generated by Django 3.0.8 on 2020-08-05 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20200805_1510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='driver_status',
            field=models.CharField(choices=[('1', 'Free'), ('2', 'Busy')], default='1', max_length=1, verbose_name='Driver Status'),
        ),
    ]
