# Generated by Django 3.0.5 on 2020-07-29 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_driver_usermodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='ranking',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='driver',
            name='rating',
            field=models.FloatField(default=-1),
        ),
    ]
