# Generated by Django 3.0.8 on 2020-08-16 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20200815_0314'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='authorizer',
            name='is_authorizer',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='is_customer',
        ),
        migrations.RemoveField(
            model_name='driver',
            name='is_driver',
        ),
    ]
