# Generated by Django 3.0.5 on 2020-07-29 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_authorizer_customer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='authorizer',
            options={'verbose_name': 'Authorizer'},
        ),
    ]
