# Generated by Django 3.0.5 on 2020-07-29 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20200729_1810'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='authorizer',
            options={'verbose_name': 'Authorizer', 'verbose_name_plural': 'Authorizers'},
        ),
        migrations.AlterModelOptions(
            name='customer',
            options={'verbose_name': 'Customer', 'verbose_name_plural': 'Customers'},
        ),
        migrations.AlterModelOptions(
            name='driver',
            options={'verbose_name': 'Driver', 'verbose_name_plural': 'Drivers'},
        ),
    ]
